apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etherdraw
    app.kubernetes.io/component: etherdraw
    app.kubernetes.io/instance: etherdraw
    app.kubernetes.io/part-of: etherdraw
  name: etherdraw
  namespace: collaboration-tools
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etherdraw
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etherdraw
        istio.io/rev: 1-13
    spec:
      containers:
      - image: quay.io/podium/etherdraw:latest
        imagePullPolicy: Always
        name: etherdraw
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etherdraw
    app.kubernetes.io/component: etherdraw
    app.kubernetes.io/instance: etherdraw
    app.kubernetes.io/part-of: etherdraw
  name: etherdraw
  namespace: collaboration-tools
spec:
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: etherdraw
  sessionAffinity: None
  type: ClusterIP