apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: etherpad
    app.kubernetes.io/component: etherpad
    app.kubernetes.io/instance: etherpad
    app.kubernetes.io/part-of: etherpad
  name: etherpad
  namespace: collaboration-tools
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: etherpad
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: etherpad
        istio.io/rev: 1-13
    spec:
      containers:
      - image: etherpad/etherpad:latest
        imagePullPolicy: Always
        name: etherpad
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etherpad
    app.kubernetes.io/component: etherpad
    app.kubernetes.io/instance: etherpad
    app.kubernetes.io/part-of: etherpad
  name: etherpad
  namespace: collaboration-tools
spec:
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: etherpad
  sessionAffinity: None
  type: ClusterIP