apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: argocd
  namespace: argocd
spec:
  applyToRoutes:
  - route:
      labels:
        argocd-oauth: "true"
  config:
    server:
      name: mgmt-ext-auth-server
      namespace: gloo-mesh
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://argocd.kapoozi.com
            callbackPath: /callback
            clientId: 0oa5rvfoqiVMovH2C5d7
            clientSecretRef:
              name: argocd-okta-client-secret
              namespace: argocd
            issuerUrl: https://dev-22653158.okta.com/oauth2/default
            session:
              failOnFetchFailure: false
              redis:
                cookieName: argocd-okta-session
                options:
                  host: redis.gloo-mesh-addons:6379
                allowRefreshing: false
              cookieOptions:
                maxAge: "1800"
            scopes:
            - email
            logoutPath: /logout
            #afterLogoutUrl: /get
            headers:
              idTokenHeader: Jwt
              #idTokenHeader: x-id-token
              #accessTokenHeader: x-access-token