apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: productpage
  namespace: bookinfo-frontends
spec:
  hosts:
  - 'productpage.asayah.solo.io'
  http:
  - forwardTo:
      destinations:
      - port:
          number: 9080
        ref:
          name: productpage
          namespace: bookinfo-frontends
    labels:
      oauth: "productpage"
    matchers:
    - uri:
        prefix: /
    name: productpage
  virtualGateways:
  - cluster: cluster1
    name: mgmt-north-south-gw-443
    namespace: istio-gateways
  workloadSelectors: []