apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: httpbin
  namespace: httpbin
spec:
  applyToRoutes:
  - route:
      labels:
        oauth: "httpbin"
  config:
    server:
      name: ext-auth-server
      namespace: httpbin
      cluster: mgmt
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode:
            appUrl: https://httpbin.asayah.solo.io
            callbackPath: /callback
            clientId: 0oa5x7fu2cbANDkVE5d7
            clientSecretRef:
              name: oauth-httpbin
              namespace: httpbin
            issuerUrl: "https://dev-44147543.okta.com/oauth2/default"
            session:
              failOnFetchFailure: true
              redis:
                cookieName: httpbin-session
                options:
                  host: redis:6379
            scopes:
            - email
            headers:
              idTokenHeader: jwt